irembo:
  outputs:
    dev:
      dbname: irembo
      host: postgres
      pass: analyst
      port: 5432
      schema: analytics
      threads: 4
      type: postgres
      user: analyst
  target: dev
